-- Seed countries
INSERT INTO countries (name, iso_code, is_active) VALUES
('Afghanistan', 'AF', FALSE),
('Albania', 'AL', FALSE),
('Algeria', 'DZ', FALSE),
('Andorra', 'AD', FALSE),
('Angola', 'AO', FALSE),
('Antigua and Barbuda', 'AG', FALSE),
('Argentina', 'AR', FALSE),
('Armenia', 'AM', FALSE),
('Australia', 'AU', FALSE),
('Austria', 'AT', FALSE),
('Azerbaijan', 'AZ', FALSE),
('Bahamas', 'BS', FALSE),
('Bahrain', 'BH', FALSE),
('Bangladesh', 'BD', FALSE),
('Barbados', 'BB', FALSE),
('Belarus', 'BY', FALSE),
('Belgium', 'BE', FALSE),
('Belize', 'BZ', FALSE),
('Benin', 'BJ', FALSE),
('Bhutan', 'BT', FALSE),
('Bolivia', 'BO', FALSE),
('Bosnia and Herzegovina', 'BA', FALSE),
('Botswana', 'BW', FALSE),
('Brazil', 'BR', FALSE),
('Brunei', 'BN', FALSE),
('Bulgaria', 'BG', FALSE),
('Burkina Faso', 'BF', FALSE),
('Burundi', 'BI', FALSE),
('Cabo Verde', 'CV', FALSE),
('Cambodia', 'KH', FALSE),
('Cameroon', 'CM', FALSE),
('Canada', 'CA', FALSE),
('Central African Republic', 'CF', FALSE),
('Chad', 'TD', FALSE),
('Chile', 'CL', FALSE),
('China', 'CN', FALSE),
('Colombia', 'CO', FALSE),
('Comoros', 'KM', FALSE),
('Congo', 'CG', FALSE),
('Costa Rica', 'CR', FALSE),
('Croatia', 'HR', FALSE),
('Cuba', 'CU', FALSE),
('Cyprus', 'CY', FALSE),
('Czech Republic', 'CZ', FALSE),
('Denmark', 'DK', FALSE),
('Djibouti', 'DJ', FALSE),
('Dominica', 'DM', FALSE),
('Dominican Republic', 'DO', FALSE),
('Ecuador', 'EC', FALSE),
('Egypt', 'EG', FALSE),
('El Salvador', 'SV', FALSE),
('Equatorial Guinea', 'GQ', FALSE),
('Eritrea', 'ER', FALSE),
('Estonia', 'EE', FALSE),
('Eswatini', 'SZ', FALSE),
('Ethiopia', 'ET', FALSE),
('Fiji', 'FJ', FALSE),
('Finland', 'FI', FALSE),
('France', 'FR', FALSE),
('Gabon', 'GA', FALSE),
('Gambia', 'GM', FALSE),
('Georgia', 'GE', FALSE),
('Germany', 'DE', FALSE),
('Ghana', 'GH', TRUE),
('Greece', 'GR', FALSE),
('Grenada', 'GD', FALSE),
('Guatemala', 'GT', FALSE),
('Guinea', 'GN', FALSE),
('Guinea-Bissau', 'GW', FALSE),
('Guyana', 'GY', FALSE),
('Haiti', 'HT', FALSE),
('Honduras', 'HN', FALSE),
('Hungary', 'HU', FALSE),
('Iceland', 'IS', FALSE),
('India', 'IN', FALSE),
('Indonesia', 'ID', FALSE),
('Iran', 'IR', FALSE),
('Iraq', 'IQ', FALSE),
('Ireland', 'IE', FALSE),
('Israel', 'IL', FALSE),
('Italy', 'IT', FALSE),
('Jamaica', 'JM', FALSE),
('Japan', 'JP', FALSE),
('Jordan', 'JO', FALSE),
('Kazakhstan', 'KZ', FALSE),
('Kenya', 'KE', FALSE),
('Kiribati', 'KI', FALSE),
('Kuwait', 'KW', FALSE),
('Kyrgyzstan', 'KG', FALSE),
('Laos', 'LA', FALSE),
('Latvia', 'LV', FALSE),
('Lebanon', 'LB', FALSE),
('Lesotho', 'LS', FALSE),
('Liberia', 'LR', FALSE),
('Libya', 'LY', FALSE),
('Liechtenstein', 'LI', FALSE),
('Lithuania', 'LT', FALSE),
('Luxembourg', 'LU', FALSE),
('Madagascar', 'MG', FALSE),
('Malawi', 'MW', FALSE),
('Malaysia', 'MY', FALSE),
('Maldives', 'MV', FALSE),
('Mali', 'ML', FALSE),
('Malta', 'MT', FALSE),
('Marshall Islands', 'MH', FALSE),
('Mauritania', 'MR', FALSE),
('Mauritius', 'MU', FALSE),
('Mexico', 'MX', FALSE),
('Micronesia', 'FM', FALSE),
('Moldova', 'MD', FALSE),
('Monaco', 'MC', FALSE),
('Mongolia', 'MN', FALSE),
('Montenegro', 'ME', FALSE),
('Morocco', 'MA', FALSE),
('Mozambique', 'MZ', FALSE),
('Myanmar', 'MM', FALSE),
('Namibia', 'NA', FALSE),
('Nauru', 'NR', FALSE),
('Nepal', 'NP', FALSE),
('Netherlands', 'NL', FALSE),
('New Zealand', 'NZ', FALSE),
('Nicaragua', 'NI', FALSE),
('Niger', 'NE', FALSE),
('Nigeria', 'NG', FALSE),
('North Korea', 'KP', FALSE),
('North Macedonia', 'MK', FALSE),
('Norway', 'NO', FALSE),
('Oman', 'OM', FALSE),
('Pakistan', 'PK', FALSE),
('Palau', 'PW', FALSE),
('Palestine', 'PS', FALSE),
('Panama', 'PA', FALSE),
('Papua New Guinea', 'PG', FALSE),
('Paraguay', 'PY', FALSE),
('Peru', 'PE', FALSE),
('Philippines', 'PH', FALSE),
('Poland', 'PL', FALSE),
('Portugal', 'PT', FALSE),
('Qatar', 'QA', FALSE),
('Romania', 'RO', FALSE),
('Russia', 'RU', FALSE),
('Rwanda', 'RW', FALSE),
('Saint Kitts and Nevis', 'KN', FALSE),
('Saint Lucia', 'LC', FALSE),
('Saint Vincent and the Grenadines', 'VC', FALSE),
('Samoa', 'WS', FALSE),
('San Marino', 'SM', FALSE),
('Sao Tome and Principe', 'ST', FALSE),
('Saudi Arabia', 'SA', FALSE),
('Senegal', 'SN', FALSE),
('Serbia', 'RS', FALSE),
('Seychelles', 'SC', FALSE),
('Sierra Leone', 'SL', FALSE),
('Singapore', 'SG', FALSE),
('Slovakia', 'SK', FALSE),
('Slovenia', 'SI', FALSE),
('Solomon Islands', 'SB', FALSE),
('Somalia', 'SO', FALSE),
('South Africa', 'ZA', FALSE),
('South Korea', 'KR', FALSE),
('South Sudan', 'SS', FALSE),
('Spain', 'ES', FALSE),
('Sri Lanka', 'LK', FALSE),
('Sudan', 'SD', FALSE),
('Suriname', 'SR', FALSE),
('Sweden', 'SE', FALSE),
('Switzerland', 'CH', FALSE),
('Syria', 'SY', FALSE),
('Taiwan', 'TW', FALSE),
('Tajikistan', 'TJ', FALSE),
('Tanzania', 'TZ', FALSE),
('Thailand', 'TH', FALSE),
('Timor-Leste', 'TL', FALSE),
('Togo', 'TG', FALSE),
('Tonga', 'TO', FALSE),
('Trinidad and Tobago', 'TT', FALSE),
('Tunisia', 'TN', FALSE),
('Turkey', 'TR', FALSE),
('Turkmenistan', 'TM', FALSE),
('Tuvalu', 'TV', FALSE),
('Uganda', 'UG', FALSE),
('Ukraine', 'UA', FALSE),
('United Arab Emirates', 'AE', FALSE),
('United Kingdom', 'GB', FALSE),
('United States', 'US', FALSE),
('Uruguay', 'UY', FALSE),
('Uzbekistan', 'UZ', FALSE),
('Vanuatu', 'VU', FALSE),
('Vatican City', 'VA', FALSE),
('Venezuela', 'VE', FALSE),
('Vietnam', 'VN', FALSE),
('Yemen', 'YE', FALSE),
('Zambia', 'ZM', FALSE),
('Zimbabwe', 'ZW', FALSE);

-- Seed categories
INSERT INTO categories (name, slug, description) VALUES
('Local Dishes',   'local-dishes',   'Traditional dishes from your local culture'),
('Continental',    'continental',    'Classic European and Western cuisines'),
('Foreign Dishes', 'foreign-dishes', 'Dishes from cultures around the world'),
('Drinks',         'drinks',         'Beverages, smoothies, and traditional drinks');