package com.dishaspora.config.seed;

import com.dishaspora.common.enums.Enums.ApprovalStatus;
import com.dishaspora.common.enums.Enums.MealType;
import com.dishaspora.common.enums.Enums.RecipeCategory;
import com.dishaspora.marketplace.entity.Vendor;
import org.springframework.stereotype.Component;

import java.util.List;

import static com.dishaspora.config.seed.SeedSupport.ing;
import static com.dishaspora.config.seed.SeedSupport.st;

/**
 * Seeds the 29 international dishes that sit alongside the West African catalogue -
 * European classics, East and South-East Asian staples, and the wider global set
 * spanning India, Mexico and the Levant.
 *
 * <p>Unlike the bundled /images/recipe-N.png artwork used by the other seeders, every
 * dish here points at an external, freely-licensed Wikimedia Commons photograph of that
 * exact dish, and carries a YouTube search link for watching the preparation. That is why
 * these all go through {@link SeedSupport#recipeWithMedia}.
 *
 * <p>Margherita Pizza is deliberately absent: {@link WorldRecipeSeeder} already seeds it.
 */
@Component
public class InternationalRecipeSeeder {

    private final SeedSupport s;

    public InternationalRecipeSeeder(SeedSupport s) {
        this.s = s;
    }

    /** Italian, French, Greek and Spanish plates. */
    public void seedEurope(Vendor kitchen) {
        s.recipeWithMedia(kitchen, "Spaghetti Carbonara",
                "Roman pasta at its most disciplined — hot spaghetti tossed off the heat with egg yolk, pecorino and crackling guanciale until it turns to glossy, peppery silk.",
                RecipeCategory.CONTINENTAL, "Italian", "ITALY", MealType.DINNER,
                "https://upload.wikimedia.org/wikipedia/commons/thumb/3/33/Espaguetis_carbonara.jpg/960px-Espaguetis_carbonara.jpg",
                720, 4, 10, 20,
                "Once per week",
                "Rich in cured pork fat, egg and aged cheese — satisfying but calorie-dense, so keep it occasional and serve with a sharp green salad.",
                "Carbonara is a surprisingly young Roman classic: the first printed recipes appear only in the mid-1940s, and the earliest known mention comes in 1950 in the Italian press. Food historians link its rise to post-war Rome, when American military rations of bacon and powdered egg met local pasta cooking. Romans quickly claimed it and codified it around guanciale, pecorino Romano and egg — no cream, a point defended with real passion.",
                1, "https://www.youtube.com/results?search_query=Spaghetti%20Carbonara%20recipe",
                4.8, 214, ApprovalStatus.APPROVED,
                List.of(ing("Spaghetti", "400", "g"), ing("Guanciale", "150", "g"),
                        ing("Egg yolks", "4", "pcs"), ing("Whole egg", "1", "pcs"),
                        ing("Pecorino Romano, grated", "80", "g"),
                        ing("Black pepper, coarsely cracked", "1", "tsp"),
                        ing("Salt for the pasta water", "1", "tbsp")),
                List.of(st(1, "Bring a large pot of well-salted water to a rolling boil and drop in the spaghetti.", 10),
                        st(2, "Cut the guanciale into thick batons and render it slowly in a dry pan until the fat runs clear and the edges crisp.", 8),
                        st(3, "Whisk the yolks, whole egg, grated pecorino and cracked pepper into a thick paste in a bowl.", 3),
                        st(4, "Loosen the egg mixture with a ladle of starchy pasta water, whisking constantly so it stays smooth.", 2),
                        st(5, "Drain the pasta and toss it in the pan of guanciale fat, off the heat, to coat every strand.", 2),
                        st(6, "Pour in the egg mixture and stir vigorously off the heat until the sauce thickens to a glossy cream — never let it scramble.", 2),
                        st(7, "Plate immediately and finish with more pecorino and a final grind of black pepper.", 1)));

        s.recipeWithMedia(kitchen, "Risotto alla Milanese",
                "Milan’s golden risotto — carnaroli rice coaxed to a loose, rippling wave with saffron, marrow-rich stock and a hard beating of cold butter and parmesan.",
                RecipeCategory.CONTINENTAL, "Italian", "ITALY", MealType.DINNER,
                "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6b/Risotto_alla_milanese.JPG/960px-Risotto_alla_milanese.JPG",
                540, 4, 10, 25,
                "1-2 times per week",
                "Mostly starch finished with butter and cheese — lighter than it tastes if you keep the portion modest and pair it with a vegetable or lean protein.",
                "Saffron rice is documented in Milan from at least the early 1800s, and the dish is bound up with the city’s long trade in the spice and with rice growing in the Po Valley. A well-loved local legend attributes it to a glassworker’s apprentice at the Duomo who used saffron as a pigment and tipped it into a wedding risotto — charming, but unverified. In Milanese kitchens it is the classic bed for ossobuco, the two served together as a single plate.",
                3, "https://www.youtube.com/results?search_query=Risotto%20alla%20Milanese%20recipe",
                4.6, 132, ApprovalStatus.APPROVED,
                List.of(ing("Carnaroli rice", "320", "g"), ing("Beef or chicken stock, hot", "1200", "ml"),
                        ing("Saffron threads", "1", "tsp"), ing("Onion, finely diced", "1", "pcs"),
                        ing("Dry white wine", "120", "ml"), ing("Cold butter", "80", "g"),
                        ing("Parmigiano Reggiano, grated", "70", "g"), ing("Beef marrow", "30", "g")),
                List.of(st(1, "Steep the saffron threads in a small ladle of hot stock and set aside to bloom.", 5),
                        st(2, "Sweat the onion gently in the marrow and a knob of butter until soft but not coloured.", 6),
                        st(3, "Add the dry rice and toast it, stirring, until the grains turn translucent at the edges.", 3),
                        st(4, "Pour in the wine and let it evaporate completely.", 2),
                        st(5, "Add hot stock a ladle at a time, stirring, waiting for each addition to be absorbed before the next.", 16),
                        st(6, "Stir in the saffron infusion for the last few minutes so the colour stays vivid.", 3),
                        st(7, "Off the heat, beat in the cold butter and parmesan hard until the risotto ripples loosely on the plate.", 2)));

        s.recipeWithMedia(kitchen, "Coq au Vin",
                "Burgundy in a pot — chicken braised low and slow in red wine with lardons, pearl onions and mushrooms until the sauce turns dark, glossy and deeply savoury.",
                RecipeCategory.CONTINENTAL, "French", "FRANCE", MealType.DINNER,
                "https://upload.wikimedia.org/wikipedia/commons/3/31/Coq_au_vin.jpg",
                660, 6, 25, 90,
                "Once per week",
                "Good protein but generous in bacon fat and butter; a weekend braise best balanced with steamed greens rather than a second starch.",
                "Coq au vin belongs to the French tradition of long-braising tough, older birds — a cockerel past its prime needed hours in wine and aromatics to become tender. Though associated above all with Burgundy, regional versions exist across France using local wines, from Riesling in Alsace to the near-black wines of the Jura. Auguste Escoffier and later Julia Child helped carry it from farmhouse economy cooking to the international bistro canon.",
                4, "https://www.youtube.com/results?search_query=Coq%20au%20Vin%20recipe",
                4.7, 176, ApprovalStatus.APPROVED,
                List.of(ing("Chicken, jointed", "1600", "g"), ing("Red Burgundy or pinot noir", "750", "ml"),
                        ing("Smoked bacon lardons", "150", "g"), ing("Pearl onions", "250", "g"),
                        ing("Button mushrooms", "250", "g"), ing("Garlic", "3", "cloves"),
                        ing("Plain flour", "2", "tbsp"), ing("Butter", "40", "g"),
                        ing("Thyme", "4", "sprigs"), ing("Salt", "1", "tsp")),
                List.of(st(1, "Marinate the chicken pieces in the red wine with garlic and thyme, refrigerated, for several hours.", 20),
                        st(2, "Lift out and pat the chicken completely dry; reserve the wine.", 5),
                        st(3, "Render the lardons in a heavy casserole, remove them, then brown the chicken hard in the fat on all sides.", 15),
                        st(4, "Dust with flour, stir to coat, then pour in the reserved wine and scrape up everything stuck to the base.", 5),
                        st(5, "Cover and braise gently until the chicken is tender and pulling from the bone.", 60),
                        st(6, "Meanwhile glaze the pearl onions and sauté the mushrooms in butter until golden.", 15),
                        st(7, "Return the lardons, onions and mushrooms to the pot and reduce the sauce until it coats a spoon.", 15)));

        s.recipeWithMedia(kitchen, "Ratatouille",
                "A Provençal summer stew of aubergine, courgette, peppers and tomato, each cooked apart then folded together so every vegetable still tastes of itself.",
                RecipeCategory.CONTINENTAL, "French", "FRANCE", MealType.LUNCH,
                "https://upload.wikimedia.org/wikipedia/commons/thumb/0/03/Ratatouille-Dish.jpg/960px-Ratatouille-Dish.jpg",
                210, 4, 25, 45,
                "3-4 times per week",
                "Almost entirely vegetables cooked in olive oil — high in fibre and micronutrients, so it works as a frequent side or a light main with bread.",
                "Ratatouille comes from the region around Nice, where it began as peasant cooking built on whatever the summer garden gave up at once. The name derives from the French verb touiller, to stir or toss together. Cooking the vegetables separately before combining them is the refinement most Provençal cooks insist on, and the reason a good ratatouille tastes layered rather than muddled.",
                5, "https://www.youtube.com/results?search_query=Ratatouille%20recipe",
                4.5, 98, ApprovalStatus.APPROVED,
                List.of(ing("Aubergine", "2", "pcs"), ing("Courgette", "3", "pcs"),
                        ing("Red bell peppers", "2", "pcs"), ing("Ripe tomatoes", "600", "g"),
                        ing("Onion", "1", "pcs"), ing("Garlic", "4", "cloves"),
                        ing("Extra virgin olive oil", "6", "tbsp"), ing("Thyme and bay", "4", "sprigs"),
                        ing("Salt", "1", "tsp")),
                List.of(st(1, "Cut the aubergine into chunks, salt them and leave to drain so they cook without soaking up oil.", 20),
                        st(2, "Fry the aubergine in olive oil until browned and creamy inside, then set aside.", 12),
                        st(3, "Brown the courgette in the same pan and remove; repeat with the peppers.", 12),
                        st(4, "Soften the onion and garlic gently, then add the chopped tomatoes, thyme and bay.", 10),
                        st(5, "Simmer the tomato base until it thickens and loses its raw edge.", 15),
                        st(6, "Fold all the vegetables back in and cook briefly together so the flavours marry but nothing collapses.", 10),
                        st(7, "Rest off the heat and serve warm or at room temperature with a last drizzle of olive oil.", 10)));

        s.recipeWithMedia(kitchen, "French Onion Soup",
                "Onions caramelised until they are nearly jam, drowned in beef stock and crowned with a raft of toasted bread and bubbling, blistered Gruyère.",
                RecipeCategory.CONTINENTAL, "French", "FRANCE", MealType.DINNER,
                "https://upload.wikimedia.org/wikipedia/commons/thumb/9/92/French_Onion_Soup..JPG/960px-French_Onion_Soup..JPG",
                430, 4, 15, 75,
                "1-2 times per week",
                "Vegetable-led and modest in calories until the cheese and bread go on — keep the gratin layer thin and it sits comfortably in a weekly rotation.",
                "Onion soup is old and humble — versions were eaten across Europe for centuries as cheap, warming food. The modern gratinée version took shape in Paris in the 1800s and became inseparable from Les Halles, the central market where night workers and late revellers ate it before dawn. The bread-and-cheese crust that defines it today is a nineteenth-century restaurant flourish on a much older peasant broth.",
                6, "https://www.youtube.com/results?search_query=French%20Onion%20Soup%20recipe",
                4.6, 144, ApprovalStatus.APPROVED,
                List.of(ing("Yellow onions, thinly sliced", "1000", "g"), ing("Butter", "50", "g"),
                        ing("Beef stock", "1200", "ml"), ing("Dry white wine", "150", "ml"),
                        ing("Baguette", "8", "slices"), ing("Gruyère, grated", "150", "g"),
                        ing("Thyme", "3", "sprigs"), ing("Salt", "1", "tsp")),
                List.of(st(1, "Melt the butter in a wide heavy pot and add the sliced onions with a pinch of salt.", 5),
                        st(2, "Cook the onions over low-medium heat, stirring often, until they collapse and turn deep mahogany — this cannot be rushed.", 45),
                        st(3, "Deglaze with the white wine and let it reduce almost to nothing.", 5),
                        st(4, "Pour in the beef stock, add the thyme and simmer so the flavours settle.", 20),
                        st(5, "Toast the baguette slices until dry and crisp right through.", 5),
                        st(6, "Ladle the soup into ovenproof bowls, float the toast on top and blanket it with Gruyère.", 3),
                        st(7, "Grill until the cheese is molten, browned and creeping over the rim.", 5)));

        s.recipeWithMedia(kitchen, "Moussaka",
                "Layered Greek comfort — silky roasted aubergine, cinnamon-scented lamb ragù and a thick béchamel cap baked until deeply burnished.",
                RecipeCategory.CONTINENTAL, "Greek", "GREECE", MealType.DINNER,
                "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d7/Mousakas.jpg/960px-Mousakas.jpg",
                690, 6, 40, 60,
                "Once per week",
                "Rich on two fronts — fatty minced lamb and a butter-and-milk béchamel — so treat it as a Sunday dish and serve with a horiatiki salad.",
                "Layered aubergine and meat dishes are shared across the eastern Mediterranean and the Levant, and the name traces back to the Arabic musaqqaʿa. The specific Greek version — with its thick béchamel top — was standardised in the 1920s by chef Nikolaos Tselementes, who brought French technique into Greek home cooking through his hugely influential cookbook. That French cap is why Greek moussaka looks and eats so differently from its Turkish and Arab relatives.",
                7, "https://www.youtube.com/results?search_query=Moussaka%20recipe",
                4.7, 189, ApprovalStatus.APPROVED,
                List.of(ing("Aubergine", "3", "pcs"), ing("Minced lamb", "700", "g"),
                        ing("Onion, chopped", "1", "pcs"), ing("Chopped tomatoes", "400", "g"),
                        ing("Ground cinnamon", "1", "tsp"), ing("Milk", "750", "ml"),
                        ing("Butter", "70", "g"), ing("Plain flour", "70", "g"),
                        ing("Kefalotyri, grated", "100", "g"), ing("Olive oil", "4", "tbsp")),
                List.of(st(1, "Slice the aubergine, salt it to draw out moisture, then brush with olive oil and roast until soft and golden.", 30),
                        st(2, "Brown the minced lamb hard with the onion so it colours rather than steams.", 12),
                        st(3, "Add the tomatoes and cinnamon and simmer until the ragù is thick and no longer watery.", 25),
                        st(4, "Make the béchamel: cook butter and flour to a pale roux, then whisk in the milk until thick and smooth.", 12),
                        st(5, "Beat most of the grated cheese into the warm béchamel and season.", 3),
                        st(6, "Layer aubergine, then ragù, then the remaining aubergine in a deep dish and level the top.", 8),
                        st(7, "Pour over the béchamel, dust with the last cheese and bake until set and deeply browned.", 45),
                        st(8, "Rest before cutting so the layers hold their shape on the plate.", 20)));

        s.recipeWithMedia(kitchen, "Greek Souvlaki with Tzatziki",
                "Char-edged skewers of oregano-and-lemon marinated pork, pulled off the grill straight into warm pita with cool, garlicky tzatziki.",
                RecipeCategory.CONTINENTAL, "Greek", "GREECE", MealType.LUNCH,
                "https://upload.wikimedia.org/wikipedia/commons/6/6e/Souvlaki_457.jpg",
                520, 4, 25, 15,
                "2-3 times per week",
                "Grilled lean protein with a yoghurt-based sauce — genuinely balanced; the pita is the main thing to keep in check.",
                "Greeks have grilled small pieces of meat on skewers since antiquity — charred skewer-holding griddles have been excavated from Bronze Age Santorini, and Homer describes meat cooked on spits. The modern souvlaki, sold from street counters and eaten wrapped in pita, took its current form in twentieth-century Greek cities, above all Athens. Tzatziki, built on strained yoghurt, cucumber and garlic, shares a family line with Turkish cacik and Middle Eastern yoghurt sauces.",
                8, "https://www.youtube.com/results?search_query=Greek%20Souvlaki%20with%20Tzatziki%20recipe",
                4.8, 203, ApprovalStatus.APPROVED,
                List.of(ing("Pork shoulder, cubed", "800", "g"), ing("Olive oil", "4", "tbsp"),
                        ing("Lemon juice", "3", "tbsp"), ing("Dried oregano", "2", "tsp"),
                        ing("Garlic", "4", "cloves"), ing("Greek yoghurt", "400", "g"),
                        ing("Cucumber, grated", "1", "pcs"), ing("Pita breads", "4", "pcs"),
                        ing("Salt", "1", "tsp")),
                List.of(st(1, "Toss the pork cubes with olive oil, lemon juice, oregano, two crushed garlic cloves and salt.", 10),
                        st(2, "Marinate in the fridge so the lemon and oregano work into the meat.", 60),
                        st(3, "Squeeze the grated cucumber dry, then fold it into the yoghurt with the remaining garlic and a little olive oil.", 10),
                        st(4, "Thread the pork onto skewers, packed snugly but not crushed together.", 5),
                        st(5, "Grill over high heat, turning, until charred outside and just cooked through.", 12),
                        st(6, "Warm the pitas briefly on the grill until soft and pliable.", 2),
                        st(7, "Rest the skewers a moment, then serve in the pita with tzatziki, red onion and tomato.", 3)));

        s.recipeWithMedia(kitchen, "Paella Valenciana",
                "The original paella — rabbit, chicken and flat green beans cooked over fire with saffron rice spread thin, prized for the toasted socarrat beneath.",
                RecipeCategory.CONTINENTAL, "Spanish", "SPAIN", MealType.LUNCH,
                "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a7/Paella_Valenciana_tradicional.jpg/960px-Paella_Valenciana_tradicional.jpg",
                640, 6, 25, 50,
                "1-2 times per week",
                "A complete one-pan meal of rice, lean meat and vegetables — filling and rice-heavy, so keep portions measured.",
                "Paella was born in the rice fields and marshes around the Albufera lagoon near Valencia, cooked outdoors over orange wood by farm workers using what was to hand — rabbit, chicken, snails and field vegetables. The word paella is Valencian for the wide shallow pan itself, not the dish. Valencians are firm that seafood versions, however good, are something else entirely; the traditional recipe is now formally protected.",
                2, "https://www.youtube.com/results?search_query=Paella%20Valenciana%20recipe",
                4.7, 231, ApprovalStatus.APPROVED,
                List.of(ing("Bomba or Senia rice", "500", "g"), ing("Chicken, jointed small", "500", "g"),
                        ing("Rabbit, jointed small", "400", "g"), ing("Flat green beans", "200", "g"),
                        ing("Garrofó butter beans", "100", "g"), ing("Grated tomato", "200", "g"),
                        ing("Saffron threads", "1", "tsp"), ing("Sweet paprika", "1", "tbsp"),
                        ing("Olive oil", "5", "tbsp"), ing("Water", "1500", "ml")),
                List.of(st(1, "Heat olive oil in a wide paella pan and brown the chicken and rabbit slowly around the outer ring.", 18),
                        st(2, "Push the meat aside and fry the green beans and garrofó until they take on colour.", 6),
                        st(3, "Add the grated tomato and paprika and cook until the sofrito darkens and thickens.", 6),
                        st(4, "Pour in the water, add the saffron and salt, and simmer to build a proper broth.", 20),
                        st(5, "Scatter the rice evenly across the whole pan and level it — do not stir again from this point.", 2),
                        st(6, "Boil hard, then lower the heat and cook until the liquid is absorbed and the surface is pitted.", 18),
                        st(7, "Raise the heat for the last minute to toast the socarrat crust on the base.", 2),
                        st(8, "Rest the pan covered with a cloth before serving straight from the pan.", 5)));

        s.recipeWithMedia(kitchen, "Spanish Tortilla",
                "A thick golden cake of potato and onion set in egg — crisp at the edge, deliberately soft and just-runny at the centre.",
                RecipeCategory.CONTINENTAL, "Spanish", "SPAIN", MealType.BREAKFAST,
                "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f5/Tortilla_de_patatas_con_cebolla.jpg/960px-Tortilla_de_patatas_con_cebolla.jpg",
                380, 4, 15, 30,
                "3-4 times per week",
                "Cheap, protein-rich and made from three ingredients — the olive oil the potatoes cook in is the only thing to moderate.",
                "The tortilla de patatas appears in Spanish records in the early nineteenth century, the earliest well-known reference being an 1817 Navarrese document describing it as cheap, filling food for the poor. Potatoes, brought from the Americas centuries earlier, had by then become a staple across rural Spain. Today it is everywhere — cut into cubes as a tapa, stuffed into a bocadillo, or eaten cold from the fridge — and Spaniards argue endlessly over whether onion belongs in it.",
                4, "https://www.youtube.com/results?search_query=Spanish%20Tortilla%20recipe",
                4.6, 117, ApprovalStatus.APPROVED,
                List.of(ing("Potatoes, peeled", "700", "g"), ing("Eggs", "6", "pcs"),
                        ing("Onion, thinly sliced", "1", "pcs"), ing("Olive oil", "300", "ml"),
                        ing("Salt", "1", "tsp")),
                List.of(st(1, "Slice the potatoes thin and irregular so some pieces break down and others hold.", 10),
                        st(2, "Poach the potatoes and onion gently in plenty of olive oil until tender but uncoloured.", 20),
                        st(3, "Drain well, reserving the oil, and season the hot potatoes with salt.", 3),
                        st(4, "Beat the eggs, fold the warm potatoes through and let the mixture sit so the potato soaks up the egg.", 10),
                        st(5, "Cook in a small pan in a little of the reserved oil, drawing the edges in, until the base is set.", 6),
                        st(6, "Invert onto a plate, slide back in and cook the second side briefly, keeping the centre soft.", 4),
                        st(7, "Slide out and rest a few minutes; serve warm or at room temperature in wedges.", 5)));
    }

    /** Chinese, Japanese, Thai and Korean plates. */
    public void seedAsia(Vendor kitchen) {
        s.recipeWithMedia(kitchen, "Kung Pao Chicken",
                "Diced chicken flash-fried with dried chillies and numbing Sichuan peppercorn, glossed in a sweet-sour sauce and scattered with blistered peanuts.",
                RecipeCategory.FOREIGN, "Chinese", "CHINA", MealType.DINNER,
                "https://upload.wikimedia.org/wikipedia/commons/thumb/0/04/Kung_Pao_Chicken_1.jpg/960px-Kung_Pao_Chicken_1.jpg",
                480, 4, 20, 12,
                "1-2 times per week",
                "Lean protein and peanuts make it satisfying, but the sauce carries sugar and sodium — serve with plain rice and greens.",
                "Gong Bao ji ding is named for Ding Baozhen, a 19th-century Qing governor of Sichuan whose honorary title was gongbao, or \"palace guardian\". During the Cultural Revolution the name was politically suspect and the dish was briefly rebranded, only to return under its original title afterwards. The authentic Sichuan version leans sour and mala rather than sweet — the ketchup-heavy takeaway version is a later overseas adaptation.",
                3, "https://www.youtube.com/results?search_query=Kung%20Pao%20Chicken%20recipe",
                4.7, 188, ApprovalStatus.APPROVED,
                List.of(ing("Chicken thigh, diced", "500", "g"), ing("Roasted peanuts", "80", "g"),
                        ing("Dried red chillies", "10", "pcs"), ing("Sichuan peppercorns", "1", "tsp"),
                        ing("Light soy sauce", "2", "tbsp"), ing("Chinkiang black vinegar", "2", "tbsp"),
                        ing("Sugar", "1", "tbsp"), ing("Garlic", "3", "cloves"),
                        ing("Spring onions", "4", "pcs"), ing("Cornflour", "1", "tbsp")),
                List.of(st(1, "Toss the diced chicken with soy sauce and cornflour and let it velvet in the fridge.", 15),
                        st(2, "Whisk soy, vinegar, sugar and a splash of water into a sauce and set it beside the wok.", 3),
                        st(3, "Heat the wok until smoking, then fry dried chillies and Sichuan peppercorns for seconds until fragrant.", 1),
                        st(4, "Add the chicken in one layer and sear undisturbed before tossing to colour all sides.", 5),
                        st(5, "Throw in garlic and the white parts of the spring onion and stir-fry hard.", 1),
                        st(6, "Pour the sauce down the side of the wok and toss until it clings and glosses.", 2),
                        st(7, "Fold in peanuts and green onion tops off the heat so the nuts stay crisp.", 1)));

        s.recipeWithMedia(kitchen, "Char Siu Pork",
                "Cantonese barbecue pork lacquered in honey, maltose and five-spice until the edges char mahogany-red and the centre stays juicy.",
                RecipeCategory.FOREIGN, "Chinese", "CHINA", MealType.DINNER,
                "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fa/Char_siu_pieces.jpg/960px-Char_siu_pieces.jpg",
                520, 4, 25, 45,
                "Once per week",
                "Rich, fatty and sugar-glazed — best treated as a weekend centrepiece alongside rice and steamed greens.",
                "Char siu literally means \"fork burn\" or \"fork roast\" in Cantonese, describing the long forks that once held seasoned pork over an open fire. It is a pillar of siu mei, the roast-meat trade whose lacquered windows still define Hong Kong and Guangzhou streets. The dish travelled with Cantonese migrants worldwide, reappearing as the pork in ramen, the filling in char siu bao, and the base of Hawaii’s manapua.",
                6, "https://www.youtube.com/results?search_query=Char%20Siu%20Pork%20recipe",
                4.8, 143, ApprovalStatus.APPROVED,
                List.of(ing("Pork shoulder", "900", "g"), ing("Hoisin sauce", "3", "tbsp"),
                        ing("Honey", "3", "tbsp"), ing("Light soy sauce", "2", "tbsp"),
                        ing("Shaoxing wine", "2", "tbsp"), ing("Chinese five-spice", "1", "tsp"),
                        ing("Garlic", "4", "cloves"), ing("Fermented red bean curd", "1", "tbsp")),
                List.of(st(1, "Cut the pork shoulder into long strips about three fingers thick so every piece gets crust.", 10),
                        st(2, "Blend hoisin, soy, Shaoxing, five-spice, garlic and red bean curd into a marinade.", 5),
                        st(3, "Reserve a third of the marinade for glazing, then coat the pork in the rest and chill overnight.", 10),
                        st(4, "Roast on a rack over a water-filled tray at high heat, turning once.", 25),
                        st(5, "Stir honey into the reserved marinade and brush the pork generously.", 3),
                        st(6, "Return to the oven and glaze twice more until the edges blacken and blister.", 15),
                        st(7, "Rest ten minutes, then slice across the grain and spoon over the pan juices.", 10)));

        s.recipeWithMedia(kitchen, "Xiaolongbao Soup Dumplings",
                "Pleated parcels of pork holding a mouthful of hot broth, steamed in bamboo and eaten in one careful, scalding bite.",
                RecipeCategory.FOREIGN, "Chinese", "CHINA", MealType.LUNCH,
                "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5e/Xiaolongbao_Shanghai.jpg/960px-Xiaolongbao_Shanghai.jpg",
                390, 4, 60, 10,
                "2-3 times per month",
                "Modest in calories but labour-intensive and salty from the aspic — a project dish rather than a weeknight staple.",
                "Xiaolongbao emerged in Nanxiang, a town on the outskirts of Shanghai, in the 1870s, and the Nanxiang Mantou Dian still trades on that lineage. The famous soup is no trick: cooled pork-skin aspic is folded into the filling and melts back into broth in the steamer. The name refers to the xiaolong, the small bamboo basket the dumplings are steamed and served in.",
                2, "https://www.youtube.com/results?search_query=Xiaolongbao%20Soup%20Dumplings%20recipe",
                4.9, 207, ApprovalStatus.APPROVED,
                List.of(ing("Plain flour", "300", "g"), ing("Warm water", "150", "ml"),
                        ing("Ground pork", "400", "g"), ing("Pork skin aspic, chilled and diced", "200", "g"),
                        ing("Ginger, grated", "1", "tbsp"), ing("Light soy sauce", "2", "tbsp"),
                        ing("Shaoxing wine", "1", "tbsp"), ing("Sesame oil", "1", "tsp"),
                        ing("Spring onions", "3", "pcs")),
                List.of(st(1, "Work flour and warm water into a smooth dough, then rest it under a cloth.", 30),
                        st(2, "Mix pork with ginger, soy, Shaoxing, sesame oil and spring onion, stirring one direction until sticky.", 8),
                        st(3, "Fold the diced aspic through the filling and chill it firm.", 20),
                        st(4, "Roll the dough into small balls and press each into a thin round with a thicker centre.", 25),
                        st(5, "Spoon in filling and pleat the edge upward, twisting the top closed.", 20),
                        st(6, "Steam in a lined bamboo basket over rolling water until the skins turn translucent.", 8),
                        st(7, "Serve with slivered ginger in black vinegar; nip the skin, sip the soup, then eat.", 2)));

        s.recipeWithMedia(kitchen, "Chicken Katsu Curry",
                "A panko-crusted chicken cutlet sliced over rice and flooded with thick, gently sweet Japanese curry sauce.",
                RecipeCategory.FOREIGN, "Japanese", "JAPAN", MealType.DINNER,
                "https://upload.wikimedia.org/wikipedia/commons/thumb/2/27/Japanese_Katsu_Curry_01.jpg/960px-Japanese_Katsu_Curry_01.jpg",
                780, 4, 20, 35,
                "Once per week",
                "Deep-fried and served over a generous bed of rice — filling comfort food that sits best as a weekly treat.",
                "Curry reached Japan in the Meiji era via the British Royal Navy, which is why kare raisu is thick and stew-like rather than loose like its Indian ancestor. The Imperial Japanese Navy adopted it as standard rations, and it spread from there into schools and homes as a national comfort food. Pairing it with tonkatsu-style breaded cutlets came later, in post-war restaurants, and katsu curry is now a fixture of Japanese diners worldwide.",
                4, "https://www.youtube.com/results?search_query=Chicken%20Katsu%20Curry%20recipe",
                4.7, 226, ApprovalStatus.APPROVED,
                List.of(ing("Chicken breasts", "4", "pcs"), ing("Panko breadcrumbs", "150", "g"),
                        ing("Eggs", "2", "pcs"), ing("Plain flour", "60", "g"),
                        ing("Onions", "2", "pcs"), ing("Carrots", "2", "pcs"),
                        ing("Japanese curry roux blocks", "4", "pcs"), ing("Chicken stock", "3", "cups"),
                        ing("Vegetable oil", "2", "cups"), ing("Short-grain rice", "2", "cups")),
                List.of(st(1, "Soften sliced onion and carrot in a pot until the onion turns golden and sweet.", 10),
                        st(2, "Add stock, simmer until the carrot is tender, then melt in the curry roux off the boil.", 15),
                        st(3, "Butterfly the chicken breasts and pound them to an even thickness.", 8),
                        st(4, "Dredge each cutlet in flour, then egg, then press firmly into panko.", 8),
                        st(5, "Shallow-fry at medium-high heat until deep golden on both sides.", 8),
                        st(6, "Drain on a rack so the crust stays crisp, then slice into thick fingers.", 3),
                        st(7, "Bed rice on one side of the plate, lay the katsu across it and ladle curry over the rice.", 3)));

        s.recipeWithMedia(kitchen, "Miso Ramen",
                "Springy noodles in a rich, fermented-soybean broth crowned with sweetcorn, butter, bamboo shoots and a jammy egg.",
                RecipeCategory.FOREIGN, "Japanese", "JAPAN", MealType.DINNER,
                "https://upload.wikimedia.org/wikipedia/commons/thumb/c/cc/Miso_ramen_in_Kochi.jpg/960px-Miso_ramen_in_Kochi.jpg",
                650, 4, 25, 40,
                "1-2 times per week",
                "Warming and protein-rich, but miso and soy push the sodium high — go easy on the broth if you are watching salt.",
                "Miso ramen is the youngest of the great ramen styles, created in Sapporo in the 1950s at a shop called Aji no Sanpei, where the owner worked miso into a pork-and-vegetable soup. Hokkaido’s brutal winters made the thick, fatty broth an obvious hit, and butter and sweetcorn became local signatures. It spread nationwide in the 1960s and remains the definitive taste of Sapporo.",
                7, "https://www.youtube.com/results?search_query=Miso%20Ramen%20recipe",
                4.8, 174, ApprovalStatus.APPROVED,
                List.of(ing("Fresh ramen noodles", "4", "pcs"), ing("Red miso paste", "4", "tbsp"),
                        ing("Chicken or pork stock", "6", "cups"), ing("Ground pork", "250", "g"),
                        ing("Garlic", "4", "cloves"), ing("Ginger, grated", "1", "tbsp"),
                        ing("Toasted sesame oil", "1", "tbsp"), ing("Eggs", "4", "pcs"),
                        ing("Sweetcorn", "1", "cups"), ing("Spring onions", "4", "pcs")),
                List.of(st(1, "Soft-boil the eggs for six and a half minutes, then chill and peel them.", 10),
                        st(2, "Fry ground pork in sesame oil with garlic and ginger until browned and crumbly.", 8),
                        st(3, "Stir the miso paste directly into the pork and let it toast until nutty.", 3),
                        st(4, "Pour in the stock and simmer gently — never boil, or the miso turns grainy.", 15),
                        st(5, "Cook the noodles separately in plenty of water so the broth stays clear of starch.", 3),
                        st(6, "Drain the noodles hard and nest them into warmed bowls.", 2),
                        st(7, "Ladle over broth and pork, then top with corn, halved egg and spring onion.", 3)));

        s.recipeWithMedia(kitchen, "Chirashi Sushi Bowl",
                "Seasoned sushi rice scattered with glistening sashimi, ribbons of egg and pickles — sushi without the folding.",
                RecipeCategory.FOREIGN, "Japanese", "JAPAN", MealType.LUNCH,
                "https://upload.wikimedia.org/wikipedia/commons/thumb/9/90/Chirashi-zushi.jpg/960px-Chirashi-zushi.jpg",
                520, 4, 35, 20,
                "2-3 times per week",
                "Lean fish, vegetables and modest fat make this one of the lighter celebration dishes — just keep the soy sauce restrained.",
                "Chirashizushi means \"scattered sushi\", and it belongs to a home-cooking tradition far older than the polished nigiri counters of Tokyo. It is the sushi of celebration: families across Japan make it for Hinamatsuri, the Doll Festival on 3 March, where its colours stand in for spring. Regional versions vary enormously, from Osaka’s cooked-and-simmered toppings to the raw seafood style now common in restaurants.",
                5, "https://www.youtube.com/results?search_query=Chirashi%20Sushi%20Bowl%20recipe",
                4.6, 96, ApprovalStatus.APPROVED,
                List.of(ing("Short-grain sushi rice", "3", "cups"), ing("Rice vinegar", "4", "tbsp"),
                        ing("Sugar", "2", "tbsp"), ing("Sashimi-grade salmon and tuna", "400", "g"),
                        ing("Eggs", "3", "pcs"), ing("Cucumber", "1", "pcs"),
                        ing("Nori", "2", "sheets"), ing("Pickled ginger", "3", "tbsp"),
                        ing("Salmon roe", "4", "tbsp")),
                List.of(st(1, "Rinse the rice until the water runs clear, then cook it and let it steam covered.", 25),
                        st(2, "Warm vinegar, sugar and salt until dissolved to make the sushi-zu.", 3),
                        st(3, "Fold the dressing through the hot rice with a cutting motion while fanning it cool.", 8),
                        st(4, "Beat the eggs thin, cook them into flat omelettes and shred into fine ribbons.", 8),
                        st(5, "Slice the fish across the grain into clean, even sashimi pieces.", 10),
                        st(6, "Spread the cooled rice into a wide bowl or lacquer tray.", 3),
                        st(7, "Scatter over egg, fish, cucumber, roe, shredded nori and pickled ginger.", 5)));

        s.recipeWithMedia(kitchen, "Pad Thai",
                "Rice noodles tossed hard in a wok with tamarind, palm sugar and fish sauce, finished with crushed peanuts and a squeeze of lime.",
                RecipeCategory.FOREIGN, "Thai", "THAILAND", MealType.LUNCH,
                "https://upload.wikimedia.org/wikipedia/commons/thumb/a/ac/Pad_thai_mound.jpg/960px-Pad_thai_mound.jpg",
                590, 4, 25, 15,
                "1-2 times per week",
                "Balanced with egg, tofu and bean sprouts, though palm sugar and fish sauce make it sweet and salty — bulk it up with extra vegetables.",
                "Pad thai was actively promoted as a national dish in the late 1930s and 40s under Prime Minister Plaek Phibunsongkhram, whose government pushed rice noodles to cut domestic rice consumption and to forge a modern Thai identity. The stir-fried-noodle technique itself is Chinese in origin, reworked with Thai tamarind, palm sugar and fish sauce. What began as state campaign became genuine street food, and it is now the dish most of the world associates with Thailand.",
                1, "https://www.youtube.com/results?search_query=Pad%20Thai%20recipe",
                4.8, 241, ApprovalStatus.APPROVED,
                List.of(ing("Flat rice noodles", "300", "g"), ing("Prawns", "300", "g"),
                        ing("Firm tofu, cubed", "150", "g"), ing("Eggs", "2", "pcs"),
                        ing("Tamarind paste", "3", "tbsp"), ing("Palm sugar", "3", "tbsp"),
                        ing("Fish sauce", "3", "tbsp"), ing("Bean sprouts", "2", "cups"),
                        ing("Roasted peanuts, crushed", "60", "g"), ing("Garlic chives", "1", "cups")),
                List.of(st(1, "Soak the rice noodles in warm water until pliable but still firm.", 20),
                        st(2, "Melt palm sugar with tamarind and fish sauce into a glossy pad thai sauce.", 5),
                        st(3, "Sear the tofu in a screaming-hot wok until the edges brown, then push it aside.", 4),
                        st(4, "Add prawns and cook just until they curl and turn opaque.", 2),
                        st(5, "Crack in the eggs, scramble them roughly, then add the drained noodles and sauce.", 3),
                        st(6, "Toss constantly over high heat until the noodles absorb the sauce and gloss.", 3),
                        st(7, "Fold in bean sprouts and chives off the heat, then serve with peanuts and lime.", 2)));

        s.recipeWithMedia(kitchen, "Green Curry with Chicken",
                "Coconut milk split with fiery green paste, simmered with chicken, pea aubergines and torn kaffir lime leaves.",
                RecipeCategory.FOREIGN, "Thai", "THAILAND", MealType.DINNER,
                "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e5/Thai_green_chicken_curry_and_roti.jpg/960px-Thai_green_chicken_curry_and_roti.jpg",
                540, 4, 20, 25,
                "1-2 times per week",
                "Vegetable-heavy and aromatic, but full-fat coconut milk brings serious saturated fat — a smaller bowl with more rice balances it.",
                "Kaeng khiao wan means \"sweet green curry\" — the sweet refers to the colour, not the taste, which is properly hot and salty. It is a central Thai curry documented from the early 20th century, its green coming from fresh bird’s eye chillies pounded with lemongrass, galangal, coriander root and shrimp paste. Coconut cream was traditionally cracked to release its oil before the paste went in, a step that separates a good curry from a flat one.",
                8, "https://www.youtube.com/results?search_query=Thai%20Green%20Curry%20with%20Chicken%20recipe",
                4.7, 158, ApprovalStatus.APPROVED,
                List.of(ing("Chicken thigh, sliced", "600", "g"), ing("Green curry paste", "4", "tbsp"),
                        ing("Coconut milk", "600", "ml"), ing("Thai aubergines", "6", "pcs"),
                        ing("Bamboo shoots", "1", "cups"), ing("Fish sauce", "2", "tbsp"),
                        ing("Palm sugar", "1", "tbsp"), ing("Kaffir lime leaves", "5", "pcs"),
                        ing("Thai basil", "1", "cups")),
                List.of(st(1, "Simmer the thick cream from the top of the coconut milk until the oil separates.", 6),
                        st(2, "Fry the green curry paste in that oil until deeply fragrant and darkened.", 4),
                        st(3, "Add the chicken and turn it through the paste until sealed on all sides.", 4),
                        st(4, "Pour in the remaining coconut milk and bring to a bare simmer.", 3),
                        st(5, "Add aubergines and bamboo shoots and cook until just tender.", 8),
                        st(6, "Season with fish sauce and palm sugar, tasting for the salty-sweet-hot balance.", 2),
                        st(7, "Tear in lime leaves and Thai basil off the heat and serve with jasmine rice.", 2)));

        s.recipeWithMedia(kitchen, "Bibimbap",
                "A bowl of rice ringed with seasoned vegetables, beef and a runny egg, all mixed hard with gochujang before the first bite.",
                RecipeCategory.FOREIGN, "Korean", "SOUTH KOREA", MealType.LUNCH,
                "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f5/Korean.food-Bibimbap-02.jpg/960px-Korean.food-Bibimbap-02.jpg",
                610, 4, 35, 25,
                "3-4 times per week",
                "One of the best-balanced bowls there is — vegetables, protein and rice in one dish, with the gochujang the only real sodium concern.",
                "Bibimbap simply means \"mixed rice\", and the earliest written reference appears as goldongban in the 19th-century Korean cookbook Siuijeonseo. Jeonju in North Jeolla Province is its most famous home, where the rice is cooked in beef broth and the vegetable namul are counted as a point of local pride. Beyond restaurants, it has long been practical food — a way to gather leftover banchan into one bowl, and the dish served at ancestral rites once the offerings came down from the table.",
                2, "https://www.youtube.com/results?search_query=Bibimbap%20recipe",
                4.9, 219, ApprovalStatus.APPROVED,
                List.of(ing("Short-grain rice", "3", "cups"), ing("Beef sirloin, sliced thin", "300", "g"),
                        ing("Spinach", "200", "g"), ing("Carrots, julienned", "2", "pcs"),
                        ing("Shiitake mushrooms", "150", "g"), ing("Bean sprouts", "2", "cups"),
                        ing("Eggs", "4", "pcs"), ing("Gochujang", "4", "tbsp"),
                        ing("Toasted sesame oil", "2", "tbsp"), ing("Garlic", "3", "cloves")),
                List.of(st(1, "Cook the rice and keep it hot and covered.", 25),
                        st(2, "Marinate the beef in soy, garlic and sesame oil while you prepare the namul.", 15),
                        st(3, "Blanch spinach and bean sprouts separately, squeeze dry and dress each with sesame oil and garlic.", 12),
                        st(4, "Stir-fry the carrot and the mushrooms separately so each keeps its own colour and flavour.", 8),
                        st(5, "Sear the marinated beef quickly over high heat until caramelised at the edges.", 4),
                        st(6, "Fry the eggs sunny side up, keeping the yolks soft.", 4),
                        st(7, "Arrange rice in bowls, fan the toppings over it in sections, crown with egg and gochujang.", 5)));

        s.recipeWithMedia(kitchen, "Korean Fried Chicken",
                "Double-fried wings shattering under a sticky gochujang glaze, sesame-flecked and impossible to eat quietly.",
                RecipeCategory.FOREIGN, "Korean", "SOUTH KOREA", MealType.SNACK,
                "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6a/Yangnyeom_Chicken_Korean_fried_chicken.jpg/960px-Yangnyeom_Chicken_Korean_fried_chicken.jpg",
                700, 4, 25, 30,
                "2-3 times per month",
                "Twice-fried and sugar-glazed — a genuine indulgence best kept to occasions, with pickled radish to cut the richness.",
                "Fried chicken arrived in Korea with American troops around the Korean War, but the modern style took shape in the 1970s and 80s as cooking oil became affordable and chains like Lims Chicken spread. The double-fry technique and thin starch coating produce a crust that survives saucing — the key innovation over its American ancestor. Yangnyeom, the sweet-spicy glazed version, dates to the mid-1980s, and chimaek, chicken with beer, is now a national pastime.",
                4, "https://www.youtube.com/results?search_query=Korean%20Fried%20Chicken%20recipe",
                4.8, 253, ApprovalStatus.APPROVED,
                List.of(ing("Chicken wings", "1000", "g"), ing("Potato starch", "150", "g"),
                        ing("Gochujang", "3", "tbsp"), ing("Soy sauce", "2", "tbsp"),
                        ing("Rice syrup or honey", "3", "tbsp"), ing("Garlic, minced", "4", "cloves"),
                        ing("Rice vinegar", "1", "tbsp"), ing("Vegetable oil", "4", "cups"),
                        ing("Toasted sesame seeds", "1", "tbsp")),
                List.of(st(1, "Pat the wings bone dry and toss them thoroughly in potato starch.", 10),
                        st(2, "Fry at moderate heat until pale gold and just cooked through, then drain.", 10),
                        st(3, "Rest the wings on a rack so steam escapes and the crust sets.", 10),
                        st(4, "Raise the oil temperature and fry a second time until deeply crisp and blistered.", 5),
                        st(5, "Simmer gochujang, soy, rice syrup, garlic and vinegar into a glossy glaze.", 5),
                        st(6, "Toss the hot wings through the glaze in a wide bowl until fully coated.", 2),
                        st(7, "Scatter sesame seeds and serve at once with pickled radish cubes.", 2)));
    }

    /** Indian, Mexican and Levantine plates. */
    public void seedGlobal(Vendor kitchen) {
        s.recipeWithMedia(kitchen, "Butter Chicken",
                "Charred tandoori chicken swimming in a velvet tomato-cream gravy, finished with a knob of butter and a crush of dried fenugreek.",
                RecipeCategory.FOREIGN, "Indian", "INDIA", MealType.DINNER,
                "https://upload.wikimedia.org/wikipedia/commons/thumb/5/56/Butter_Chicken.jpg/960px-Butter_Chicken.jpg",
                590, 4, 30, 40,
                "Once a week",
                "Cream and butter make this rich; keep the portion modest, skip the second naan, and lean on a cucumber salad alongside.",
                "Butter chicken — murgh makhani — was invented in the 1950s at Moti Mahal in Delhi, where cooks who had fled Peshawar during Partition rescued unsold tandoori chicken by simmering it in a tomato, butter and cream gravy. What began as thrift became one of the most recognised Indian dishes on earth. Its Punjabi refugee origins are why it tastes of the tandoor first and the sauce second.",
                1, "https://www.youtube.com/results?search_query=Butter%20Chicken%20recipe",
                4.8, 214, ApprovalStatus.APPROVED,
                List.of(ing("Chicken thighs, boneless", "800", "g"), ing("Thick yoghurt", "200", "g"),
                        ing("Ginger-garlic paste", "2", "tbsp"), ing("Tomato puree", "500", "ml"),
                        ing("Butter", "80", "g"), ing("Double cream", "150", "ml"),
                        ing("Kashmiri chilli powder", "2", "tsp"), ing("Garam masala", "1", "tsp"),
                        ing("Dried fenugreek leaves", "1", "tbsp")),
                List.of(st(1, "Marinate the chicken in yoghurt, ginger-garlic paste, chilli powder and salt.", 30),
                        st(2, "Grill or pan-sear the chicken hard until edges blacken; set aside with its juices.", 12),
                        st(3, "Melt butter, bloom the remaining spices, then pour in the tomato puree.", 5),
                        st(4, "Simmer the gravy until it thickens and the butter separates at the edges.", 15),
                        st(5, "Blend the sauce smooth if you want the restaurant texture, then return it to the pan.", 5),
                        st(6, "Slide in the chicken, stir through cream and crushed fenugreek, and simmer gently.", 8),
                        st(7, "Finish with an extra knob of butter and serve with naan or basmati.", 0)));

        s.recipeWithMedia(kitchen, "Chana Masala",
                "Chickpeas stewed down in a dark, tangy onion-tomato masala until the gravy clings to every pea and the amchur cuts clean through it.",
                RecipeCategory.FOREIGN, "Indian", "INDIA", MealType.LUNCH,
                "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7f/Chana_masala_gravy.JPG/960px-Chana_masala_gravy.JPG",
                340, 4, 15, 40,
                "3-4 times per week",
                "High in plant protein and fibre with very little added fat — one of the easiest weeknight dishes to eat often.",
                "Chana masala belongs to the Punjabi and Delhi street kitchens of north India, where it is paired with fried bhatura bread for the classic chole bhature. The signature sourness comes from amchur or pomegranate seed powder rather than the tamarind used further south. Chickpeas have grown across the subcontinent for millennia, which is part of why the dish reads as ordinary and beloved rather than special-occasion.",
                4, "https://www.youtube.com/results?search_query=Chana%20Masala%20recipe",
                4.6, 178, ApprovalStatus.APPROVED,
                List.of(ing("Chickpeas, cooked", "500", "g"), ing("Onions", "2", "pcs"),
                        ing("Tomatoes", "4", "pcs"), ing("Ginger-garlic paste", "1", "tbsp"),
                        ing("Ground cumin", "2", "tsp"), ing("Ground coriander", "2", "tsp"),
                        ing("Amchur (dried mango powder)", "1", "tsp"), ing("Garam masala", "1", "tsp"),
                        ing("Vegetable oil", "3", "tbsp")),
                List.of(st(1, "Fry finely chopped onion in oil until deeply browned, not just soft.", 12),
                        st(2, "Add ginger-garlic paste and cook off the raw smell.", 2),
                        st(3, "Stir in cumin, coriander and chilli, then the chopped tomatoes.", 3),
                        st(4, "Cook the masala down until it darkens and oil pools at the sides.", 12),
                        st(5, "Add the chickpeas with a splash of their cooking water; mash a few against the pan to thicken.", 10),
                        st(6, "Finish with amchur and garam masala, then rest off the heat before serving.", 5)));

        s.recipeWithMedia(kitchen, "Lamb Biryani",
                "Spiced lamb and half-cooked basmati layered in a sealed pot and steamed until the rice runs from saffron gold to white in a single spoonful.",
                RecipeCategory.FOREIGN, "Indian", "INDIA", MealType.DINNER,
                "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ed/Lamb_Biryani_-_Biryani_House_AUD8.50_%283643374430%29.jpg/960px-Lamb_Biryani_-_Biryani_House_AUD8.50_%283643374430%29.jpg",
                720, 6, 45, 75,
                "Once a week",
                "Rich in fatty lamb, ghee and rice — treat it as the centrepiece of one meal rather than a regular weekday plate.",
                "Biryani arrived with Persian-influenced Mughal court cooking and then splintered into fiercely defended regional styles — Hyderabadi, Lucknawi, Kolkata, Malabar — each arguing over spice level, whether the meat is raw-cooked in the pot, and what belongs under the lid. The dum method of sealing the vessel with dough traps steam and aroma so the rice cooks in the lamb’s own perfume. Kolkata’s version famously carries a potato, a legacy of Awadhi cooks stretching expensive meat further.",
                6, "https://www.youtube.com/results?search_query=Lamb%20Biryani%20recipe",
                4.9, 246, ApprovalStatus.APPROVED,
                List.of(ing("Lamb shoulder, bone-in", "1000", "g"), ing("Basmati rice", "4", "cups"),
                        ing("Thick yoghurt", "300", "g"), ing("Onions", "4", "pcs"),
                        ing("Ghee", "6", "tbsp"), ing("Biryani masala", "3", "tbsp"),
                        ing("Saffron strands", "1", "tsp"), ing("Mint and coriander", "2", "cups"),
                        ing("Milk, warm", "100", "ml")),
                List.of(st(1, "Fry sliced onions in ghee until crisp and dark; drain and reserve the birista.", 20),
                        st(2, "Marinate lamb in yoghurt, biryani masala, half the fried onions and salt.", 40),
                        st(3, "Cook the marinated lamb until tender and the gravy is thick, not watery.", 45),
                        st(4, "Boil soaked basmati in heavily salted water to 70 percent done, then drain.", 8),
                        st(5, "Layer lamb, rice, herbs and fried onions; pour over saffron steeped in warm milk.", 5),
                        st(6, "Seal the pot with dough or foil and steam on the lowest heat — this is the dum.", 25),
                        st(7, "Rest sealed for ten minutes, then lift from the bottom so each plate gets both layers.", 10)));

        s.recipeWithMedia(kitchen, "Masala Dosa",
                "A fermented rice-and-lentil crepe spread paper-thin on a screaming griddle, wrapped around soft turmeric potatoes and served with sambar and coconut chutney.",
                RecipeCategory.FOREIGN, "Indian", "INDIA", MealType.BREAKFAST,
                "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f4/Masala_Dosa.jpg/960px-Masala_Dosa.jpg",
                430, 4, 30, 30,
                "2-3 times per week",
                "Fermentation makes the batter easy to digest and the filling is vegetable-led; just go light on the ghee at the griddle.",
                "The dosa is a South Indian staple with a long documented history in Tamil literature, but the potato-stuffed masala dosa is widely traced to Karnataka, and Bengaluru institutions such as Vidyarthi Bhavan and MTR are credited with popularising the form it takes today. The batter’s overnight fermentation is the whole trick — wild yeasts and lactic bacteria give it both lift and that faint sourness. It travelled north with Udupi restaurants until it became India’s most portable breakfast.",
                2, "https://www.youtube.com/results?search_query=Masala%20Dosa%20recipe",
                4.7, 163, ApprovalStatus.APPROVED,
                List.of(ing("Rice", "3", "cups"), ing("Urad dal", "1", "cups"),
                        ing("Fenugreek seeds", "1", "tsp"), ing("Potatoes", "5", "pcs"),
                        ing("Onions", "2", "pcs"), ing("Mustard seeds", "1", "tsp"),
                        ing("Curry leaves", "2", "sprigs"), ing("Turmeric", "1", "tsp"),
                        ing("Ghee", "4", "tbsp")),
                List.of(st(1, "Soak rice, urad dal and fenugreek separately for at least four hours.", 30),
                        st(2, "Grind to a smooth batter, salt it, and leave overnight to ferment until risen and sour.", 20),
                        st(3, "Temper mustard seeds and curry leaves, add onion, turmeric and boiled crushed potatoes.", 15),
                        st(4, "Heat a flat griddle until a water drop dances, then wipe it with a halved onion.", 3),
                        st(5, "Pour a ladle of batter and spiral it outward with the ladle base into a thin disc.", 2),
                        st(6, "Drizzle ghee around the rim and cook until the underside is lacquered and crisp.", 3),
                        st(7, "Spoon potato masala down the centre, fold, and serve with sambar and coconut chutney.", 2)));

        s.recipeWithMedia(kitchen, "Chicken Tacos al Pastor",
                "Achiote-and-chilli marinated chicken seared hard, piled into warm corn tortillas with charred pineapple, onion and coriander.",
                RecipeCategory.FOREIGN, "Mexican", "MEXICO", MealType.DINNER,
                "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e7/Al_pastor_tacos.jpg/960px-Al_pastor_tacos.jpg",
                480, 4, 25, 25,
                "2-3 times per week",
                "Lean chicken, corn tortillas and fresh salsa keep it light — the pineapple sugar is the only thing to watch.",
                "Tacos al pastor descend from the shawarma brought to Mexico by Lebanese immigrants in the early twentieth century, whose vertical spit was adopted in Puebla and Mexico City and reworked with pork, dried chillies and achiote. The name means \"shepherd style\", and the trompo — the spinning cone crowned with a pineapple — is the direct descendant of that Levantine grill. Chicken versions are a modern home-kitchen adaptation of a technique built for the spit.",
                7, "https://www.youtube.com/results?search_query=Chicken%20Tacos%20al%20Pastor%20recipe",
                4.7, 201, ApprovalStatus.APPROVED,
                List.of(ing("Chicken thighs, boneless", "800", "g"), ing("Guajillo chillies, dried", "4", "pcs"),
                        ing("Achiote paste", "3", "tbsp"), ing("Pineapple", "1", "pcs"),
                        ing("White vinegar", "3", "tbsp"), ing("Garlic", "4", "cloves"),
                        ing("Corn tortillas", "12", "pcs"), ing("White onion", "1", "pcs"),
                        ing("Coriander", "1", "cups")),
                List.of(st(1, "Toast the dried guajillos briefly, then soak them in hot water until pliable.", 15),
                        st(2, "Blend chillies with achiote, garlic, vinegar and a little pineapple into a thick marinade.", 5),
                        st(3, "Coat the chicken thighs and marinate, ideally several hours.", 60),
                        st(4, "Sear the chicken in a very hot pan or on a grill until the edges char.", 12),
                        st(5, "Grill thick pineapple slices alongside until caramelised, then dice both.", 6),
                        st(6, "Warm the tortillas directly on the flame until they puff and smell toasted.", 3),
                        st(7, "Fill with chicken and pineapple, top with raw onion, coriander and lime.", 0)));

        s.recipeWithMedia(kitchen, "Chiles en Nogada",
                "Roasted poblanos stuffed with sweet-savoury picadillo, blanketed in cold walnut cream and scattered with pomegranate seeds and parsley.",
                RecipeCategory.FOREIGN, "Mexican", "MEXICO", MealType.DINNER,
                "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f5/Chiles_en_nogada_cl%C3%A1sicos.jpg/960px-Chiles_en_nogada_cl%C3%A1sicos.jpg",
                640, 4, 50, 45,
                "Once or twice a month",
                "Walnut cream and fried picadillo make this dense and seasonal — it was always meant as a celebration plate.",
                "Chiles en nogada is Puebla’s most patriotic dish, its green chilli, white walnut sauce and red pomegranate matching the Mexican flag. It is eaten in a short late-summer window when fresh walnuts, pomegranates and the criollo fruit for the picadillo are all in season at once. Popular accounts link it to Agustín de Iturbide’s visit to Puebla in 1821, though the convent-kitchen attribution is tradition rather than settled history.",
                3, "https://www.youtube.com/results?search_query=Chiles%20en%20Nogada%20recipe",
                4.6, 88, ApprovalStatus.APPROVED,
                List.of(ing("Poblano chillies", "4", "pcs"), ing("Minced pork and beef", "500", "g"),
                        ing("Walnuts, shelled", "200", "g"), ing("Cream cheese", "150", "g"),
                        ing("Milk", "150", "ml"), ing("Apple and pear, diced", "2", "pcs"),
                        ing("Raisins", "60", "g"), ing("Pomegranate seeds", "1", "cups"),
                        ing("Flat-leaf parsley", "3", "sprigs")),
                List.of(st(1, "Char the poblanos over an open flame until blackened, then sweat them in a covered bowl.", 15),
                        st(2, "Peel and slit each chilli carefully, removing seeds but leaving the stem on.", 10),
                        st(3, "Fry the minced meat with onion and garlic, then add fruit, raisins and warm spices.", 20),
                        st(4, "Cook the picadillo down until glossy and barely wet, then cool slightly.", 10),
                        st(5, "Blend walnuts with cream cheese and milk into a smooth, pourable nogada and chill it.", 10),
                        st(6, "Stuff each chilli generously and set it seam-down on the plate.", 5),
                        st(7, "Pour the cold nogada over the warm chillies and finish with pomegranate and parsley.", 0)));

        s.recipeWithMedia(kitchen, "Pozole Rojo",
                "A deep red hominy and pork broth built on toasted guajillo chillies, served with a whole table of shredded cabbage, radish, oregano and lime.",
                RecipeCategory.FOREIGN, "Mexican", "MEXICO", MealType.DINNER,
                "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d4/Pozole_rojo_%282017%29.jpg/960px-Pozole_rojo_%282017%29.jpg",
                520, 6, 30, 150,
                "Once a week",
                "Long-simmered pork makes the broth fatty, but the hominy and mountain of raw garnishes balance the bowl well.",
                "Pozole is a pre-Hispanic dish — Spanish chroniclers recorded Mexica versions made with nixtamalized maize, and it carried ceremonial weight long before pork arrived with the Spanish. The hominy at its centre is corn treated with lime, the same nixtamal process that makes tortillas possible. Today the rojo, blanco and verde styles map roughly onto Jalisco, Guerrero and Guerrero-adjacent traditions, and a pot of it is standard for Mexican Independence Day.",
                5, "https://www.youtube.com/results?search_query=Pozole%20Rojo%20recipe",
                4.7, 134, ApprovalStatus.APPROVED,
                List.of(ing("Pork shoulder", "1000", "g"), ing("Hominy (cacahuazintle), cooked", "800", "g"),
                        ing("Guajillo chillies, dried", "6", "pcs"), ing("Ancho chillies, dried", "2", "pcs"),
                        ing("White onion", "1", "pcs"), ing("Garlic", "6", "cloves"),
                        ing("Dried oregano", "1", "tbsp"), ing("Radishes", "6", "pcs"),
                        ing("Cabbage, shredded", "2", "cups")),
                List.of(st(1, "Simmer the pork with onion, garlic and salt until it shreds easily; skim the broth.", 120),
                        st(2, "Toast the dried chillies until fragrant, then soak them in hot broth.", 15),
                        st(3, "Blend the soaked chillies smooth and strain the paste into the pot.", 10),
                        st(4, "Add the hominy and let everything simmer together so the broth turns properly red.", 30),
                        st(5, "Shred the pork and return it to the pot; adjust salt and oregano.", 10),
                        st(6, "Set out radish, cabbage, onion, lime and tostadas so each bowl is finished at the table.", 0)));

        s.recipeWithMedia(kitchen, "Enchiladas Verdes",
                "Corn tortillas rolled around shredded chicken, drowned in a bright tomatillo salsa and blistered under crema and crumbled cheese.",
                RecipeCategory.FOREIGN, "Mexican", "MEXICO", MealType.LUNCH,
                "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5f/Enchiladas_verdes_con_pollo.jpg/960px-Enchiladas_verdes_con_pollo.jpg",
                550, 4, 25, 35,
                "1-2 times per week",
                "The tomatillo sauce is genuinely light; the cheese and crema are what push the calories, so serve them with a hand rather than a ladle.",
                "Enchiladas are simply tortillas bathed in chilli sauce, a practice as old as the tortilla itself and recorded in Mexico’s earliest cookbooks under names like \"tortillas enchiladas\". The verde version leans on the tomatillo, a husked fruit native to Mexico and used since pre-Hispanic times, which gives the sauce its sharpness. Frying the salsa before saucing is the step home cooks skip and Mexican kitchens never do.",
                8, "https://www.youtube.com/results?search_query=Enchiladas%20Verdes%20recipe",
                4.5, 112, ApprovalStatus.APPROVED,
                List.of(ing("Tomatillos", "600", "g"), ing("Serrano chillies", "2", "pcs"),
                        ing("Chicken breast, poached", "500", "g"), ing("Corn tortillas", "12", "pcs"),
                        ing("White onion", "1", "pcs"), ing("Coriander", "1", "cups"),
                        ing("Mexican crema", "150", "ml"), ing("Queso fresco", "150", "g")),
                List.of(st(1, "Boil or roast the tomatillos with serranos, onion and garlic until they slump and dull.", 12),
                        st(2, "Blend with coriander and salt into a loose, vivid green salsa.", 5),
                        st(3, "Fry the salsa briefly in hot oil so it deepens and loses its raw edge.", 8),
                        st(4, "Shred the poached chicken and season it with a spoonful of the sauce.", 5),
                        st(5, "Soften each tortilla in warm oil or sauce so it rolls without cracking.", 8),
                        st(6, "Fill and roll the tortillas, pack them seam-down in a dish, and flood with the rest of the salsa.", 8),
                        st(7, "Top with crema and queso fresco and bake or grill just until bubbling.", 12)));

        s.recipeWithMedia(kitchen, "Falafel with Hummus",
                "Craggy, herb-green chickpea fritters fried until they crack open, spooned onto a swirl of hummus with tahini and pickles.",
                RecipeCategory.FOREIGN, "Middle Eastern", "LEBANON", MealType.LUNCH,
                "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4d/Falafel_and_Homemade_Hummus_-_Lavash_2024-09-11.jpg/960px-Falafel_and_Homemade_Hummus_-_Lavash_2024-09-11.jpg",
                510, 4, 25, 20,
                "1-2 times per week",
                "Chickpeas and tahini bring protein and good fats, but the falafel are deep-fried — bake them if you want this more often.",
                "Falafel’s origins are genuinely contested across the eastern Mediterranean: Egypt fries a fava-bean version called ta’amiya, while Levantine kitchens in Lebanon, Syria and Palestine use chickpeas, and both claim considerable antiquity. What is not contested is the technique — the chickpeas must be soaked raw, never cooked, or the fritters collapse in the oil. Hummus bi tahina has an equally long Levantine record and the pairing has become the default plate of the region’s street corners.",
                4, "https://www.youtube.com/results?search_query=Falafel%20with%20Hummus%20recipe",
                4.6, 189, ApprovalStatus.APPROVED,
                List.of(ing("Dried chickpeas, soaked overnight", "400", "g"), ing("Flat-leaf parsley", "4", "sprigs"),
                        ing("Coriander", "1", "cups"), ing("Garlic", "5", "cloves"),
                        ing("Ground cumin", "2", "tsp"), ing("Baking powder", "1", "tsp"),
                        ing("Tahini", "5", "tbsp"), ing("Lemon juice", "4", "tbsp"),
                        ing("Sunflower oil for frying", "750", "ml")),
                List.of(st(1, "Drain the soaked chickpeas thoroughly — never use tinned, and never boil them first.", 10),
                        st(2, "Grind raw chickpeas with herbs, garlic, cumin and salt to a coarse, damp crumb.", 8),
                        st(3, "Chill the mixture, then stir in baking powder just before shaping.", 30),
                        st(4, "Shape into small patties or quenelles and let them sit briefly to firm up.", 10),
                        st(5, "Reserve a third of the chickpeas, boil them soft, and blend with tahini, lemon and garlic for the hummus.", 25),
                        st(6, "Fry the falafel in hot oil until deep brown and hollow-sounding, then drain.", 10),
                        st(7, "Spread the hummus wide, pile the falafel on, and finish with tahini sauce and pickles.", 0)));

        s.recipeWithMedia(kitchen, "Lamb Kofta Kebabs",
                "Hand-moulded minced lamb, heavy with parsley, onion and warm spice, pressed onto skewers and grilled until the fat drips and flares.",
                RecipeCategory.FOREIGN, "Middle Eastern", "LEBANON", MealType.DINNER,
                "https://upload.wikimedia.org/wikipedia/commons/thumb/1/19/Grilled_Kefta_Skewers.jpg/960px-Grilled_Kefta_Skewers.jpg",
                470, 4, 25, 15,
                "1-2 times per week",
                "Red meat and lamb fat mean moderation, but grilling lets a good deal of that fat render away — serve with tabbouleh rather than chips.",
                "Kofta belongs to a vast family of spiced minced-meat dishes stretching from the Balkans through Turkey and the Levant to South Asia, with the word itself coming from the Persian kuftan, \"to pound\". The Lebanese kafta leans on parsley, onion and allspice rather than the chilli-forward Turkish adana. Grilling it on a flat skewer over charcoal is the version that anchors the mezze table and the summer garden alike.",
                7, "https://www.youtube.com/results?search_query=Lamb%20Kofta%20Kebabs%20recipe",
                4.8, 157, ApprovalStatus.APPROVED,
                List.of(ing("Minced lamb", "700", "g"), ing("Onion, grated", "1", "pcs"),
                        ing("Flat-leaf parsley", "5", "sprigs"), ing("Garlic", "3", "cloves"),
                        ing("Ground allspice", "1", "tsp"), ing("Ground cinnamon", "1", "tsp"),
                        ing("Sumac", "1", "tsp"), ing("Flatbreads", "4", "pcs")),
                List.of(st(1, "Squeeze the grated onion dry — wet onion is what makes kofta slide off the skewer.", 5),
                        st(2, "Mix lamb with onion, finely chopped parsley, garlic, allspice, cinnamon and salt.", 8),
                        st(3, "Knead the mixture firmly until it turns slightly sticky and holds together.", 5),
                        st(4, "Chill the mince so the fat firms up before shaping.", 30),
                        st(5, "Press portions around flat skewers into long, even sausages with ridged edges.", 10),
                        st(6, "Grill over high direct heat, turning once, until charred outside and just pink within.", 12),
                        st(7, "Rest on warm flatbread so the bread catches the juices, then dust with sumac.", 5)));
    }
}
